name: Build and Commit on Merge

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Ensures the history is fully checked out

      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "^2.2.12"
          cache: true

      - name: Install silverbullet with Deno
        run: |
          deno install -f --name silverbullet --global --unstable-kv --unstable-worker-options -A https://get.silverbullet.md

      - name: Build with Deno
        run: |
          set -e
          deno task build

      - name: Commit and Push meetingNote.plug.js
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add meetingNote.plug.js
          git commit -m "Auto-update meetingNote.plug.js" || echo "No changes to commit"
          git push --set-upstream origin main
